// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(SATContext))]
    partial class SATContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("AttachmentSolutionHistory", b =>
                {
                    b.Property<int>("AttachmentsAttachmentId")
                        .HasColumnType("int");

                    b.Property<int>("SolutionHistoriesSolutionHistoryId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentsAttachmentId", "SolutionHistoriesSolutionHistoryId");

                    b.HasIndex("SolutionHistoriesSolutionHistoryId");

                    b.ToTable("SolutionHistoryAttachments");
                });

            modelBuilder.Entity("Core.Entity.Annotation", b =>
                {
                    b.Property<int>("AnnotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AnnotationBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AnnotationId");

                    b.HasIndex("UserId");

                    b.ToTable("Annotation");
                });

            modelBuilder.Entity("Core.Entity.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("Char(5)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar(100)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("VarChar(1000)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("Core.Entity.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("int");

                    b.HasKey("BranchId");

                    b.HasIndex("MunicipalityId");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("Core.Entity.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Core.Entity.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CelPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PhoneExtension")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Core.Entity.Municipality", b =>
                {
                    b.Property<int>("MunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("MunicipalityId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Municipality");
                });

            modelBuilder.Entity("Core.Entity.ProblemType", b =>
                {
                    b.Property<int>("ProblemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CurrentSolutionSolutionHistoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemName")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar(100)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("ProblemTypeId");

                    b.HasIndex("CurrentSolutionSolutionHistoryId");

                    b.HasIndex("SourceId");

                    b.ToTable("ProblemType");
                });

            modelBuilder.Entity("Core.Entity.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("Core.Entity.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("RolName")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("RolId");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Core.Entity.SolutionHistory", b =>
                {
                    b.Property<int>("SolutionHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SolutionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SolutionProblemTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SolutionHistoryId");

                    b.HasIndex("SolutionProblemTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("SolutionHistory");
                });

            modelBuilder.Entity("Core.Entity.Source", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("VarChar(45)");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.HasKey("SourceId");

                    b.ToTable("Source");
                });

            modelBuilder.Entity("Core.Entity.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("ActualTime")
                        .HasColumnType("real");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<int?>("AttendedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("EstimatedTime")
                        .HasColumnType("real");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("TaskDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("AttendedByUserId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SourceId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("Core.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("VarChar(45)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VarChar(250)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VarChar(15)");

                    b.HasKey("UserId");

                    b.HasIndex("RolId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Core.Entity.TechnicalAssistance", b =>
                {
                    b.HasBaseType("Core.Entity.Task");

                    b.Property<int?>("ProblemTypeId")
                        .HasColumnType("int");

                    b.HasIndex("ProblemTypeId");

                    b.ToTable("TechnicalAssistance");
                });

            modelBuilder.Entity("AttachmentSolutionHistory", b =>
                {
                    b.HasOne("Core.Entity.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentsAttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entity.SolutionHistory", null)
                        .WithMany()
                        .HasForeignKey("SolutionHistoriesSolutionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entity.Annotation", b =>
                {
                    b.HasOne("Core.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entity.Attachment", b =>
                {
                    b.HasOne("Core.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entity.Branch", b =>
                {
                    b.HasOne("Core.Entity.Municipality", "Municipality")
                        .WithMany("Branches")
                        .HasForeignKey("MunicipalityId");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Core.Entity.Employee", b =>
                {
                    b.HasOne("Core.Entity.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("Core.Entity.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Branch");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Core.Entity.Municipality", b =>
                {
                    b.HasOne("Core.Entity.Province", "Province")
                        .WithMany("Municipalities")
                        .HasForeignKey("ProvinceId");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Core.Entity.ProblemType", b =>
                {
                    b.HasOne("Core.Entity.SolutionHistory", "CurrentSolution")
                        .WithMany()
                        .HasForeignKey("CurrentSolutionSolutionHistoryId");

                    b.HasOne("Core.Entity.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.Navigation("CurrentSolution");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Core.Entity.SolutionHistory", b =>
                {
                    b.HasOne("Core.Entity.ProblemType", "Solution")
                        .WithMany("SolutionHistories")
                        .HasForeignKey("SolutionProblemTypeId");

                    b.HasOne("Core.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Solution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entity.Task", b =>
                {
                    b.HasOne("Core.Entity.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId");

                    b.HasOne("Core.Entity.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("Core.Entity.User", "AttendedBy")
                        .WithMany()
                        .HasForeignKey("AttendedByUserId");

                    b.HasOne("Core.Entity.Employee", "Employee")
                        .WithMany("Tasks")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Core.Entity.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.Navigation("AssignedBy");

                    b.Navigation("AssignedTo");

                    b.Navigation("AttendedBy");

                    b.Navigation("Employee");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Core.Entity.User", b =>
                {
                    b.HasOne("Core.Entity.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Core.Entity.TechnicalAssistance", b =>
                {
                    b.HasOne("Core.Entity.ProblemType", "ProblemType")
                        .WithMany()
                        .HasForeignKey("ProblemTypeId");

                    b.HasOne("Core.Entity.Task", null)
                        .WithOne()
                        .HasForeignKey("Core.Entity.TechnicalAssistance", "TaskId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("ProblemType");
                });

            modelBuilder.Entity("Core.Entity.Employee", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Core.Entity.Municipality", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("Core.Entity.ProblemType", b =>
                {
                    b.Navigation("SolutionHistories");
                });

            modelBuilder.Entity("Core.Entity.Province", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("Core.Entity.Rol", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
